### PR TITLE
Drale1/10.3.x/#53 get pagespeed 100

### LINKED ISSUE #53: Get PageSpeed 100
* Get the /node/7 to PageSpeed 100.
* Optimize /node/1 to PageSpeed 100.

### PR DESCRIPTION
**Pull request by drale1**
Fixes #53 

I installed and configured Advanced Aggregation and Minify HTML to get higher pagespeed.

### CODE REVIEW

**Comment by drale1** [comment]
Fixed issue with drush cim --partial.

I installed module https://www.drupal.org/project/config_profile and added 

  config_profile: 0

to core.extension.yml

**Review by jjroelofs — CHANGES_REQUESTED** [review]
Hello, I cannot test this PR as the configuration is not compatible with how Drupal distributions work. Following the "show don't tell" aphorism I created an example pull request for you to help understand what the expected structure of your PR is:

https://github.com/dxpr/dxpr_marketing_cms/pull/55/files

We add advagg to dependencies, add it and desired submodules to the list of installed module, and add the new configuration objects that we want.

To add the new config object, you can either install and use the config_profile module, or add them manually.

**Comment by drale1** [comment]
> Hello, I cannot test this PR as the configuration is not compatible with how Drupal distributions work. Following the "show don't tell" aphorism I created an example pull request for you to help understand what the expected structure of your PR is:
> 
> https://github.com/dxpr/dxpr_marketing_cms/pull/55/files
> 
> We add advagg to dependencies, add it and desired submodules to the list of installed module, and add the new configuration objects that we want.
> 
> To add the new config object, you can either install and use the config_profile module, or add them manually.

I added all config files to install folder and manually changed composer.json and dxpr_marketing_cms.info.yml.

**Review by jjroelofs — APPROVED** [review]
Thanks, it works now but with only this PR the impact of frontend performance is not enough to make it to 100 on mobile performance on my localhost. I'm doing side-by-side comparison on the /node/7 page because this page is simplest. I only test mobile mode because in Desktop mode on Lighthouse/localhost I already get 100 PageSpeed in the old situation. I'm doing 5 runs and taking the average to compare.

On /node/7 On /node/7 without your changes:
 your changes:
(93+95+93+95+95) / 5 = **94**

I think within the scope of what we can do in this pull request, this is already a great result and I will merge it, but I'll also be in touch about possible next steps, thx!

On /node/7 **with** your changes:
(97+97+97+97+97) / 5 = **97**

Already a good result but there are a lot more points in the Lighthouse report to address:

**Comment by drale1** [comment]
> Thanks, it works now but with only this PR the impact of frontend performance is not enough to make it to 100 on mobile performance on my localhost. I'm doing side-by-side comparison on the /node/7 page because this page is simplest. I only test mobile mode because in Desktop mode on Lighthouse/localhost I already get 100 PageSpeed in the old situation. I'm doing 5 runs and taking the average to compare.
> 
> On /node/7 On /node/7 without your changes: your changes: (93+95+93+95+95) / 5 = **94**
> 
> I think within the scope of what we can do in this pull request, this is already a great result and I will merge it, but I'll also be in touch about possible next steps, thx!
> 
> On /node/7 **with** your changes: (97+97+97+97+97) / 5 = **97**
> 
> Already a good result but there are a lot more points in the Lighthouse report to address:

That was pretty similar on my side. Perhaps online with:
-CDN
-Brotli PHP extension
-jsmin php extension 
Will be on 100 mobile speed.

**Pull request merged**
