### PR TITLE
Modified existing image styles to display webp instead uploaded image…

### PR DESCRIPTION
**Pull request by drale1**
I just modified image styles to convert uploaded files to WebP

### CODE REVIEW

**Review by jjroelofs — APPROVED** [review]
great! It seems to work perfectly fine out of the box :)

**Comment by drale1** [comment]
Nice, I'm glad you like it!

**Comment by jjroelofs** [comment]
@drale1 next time please link the PR to the issue

**Comment by jjroelofs** [comment]
Fixes #56

**Pull request merged**
