### PR TITLE
Fixed #48: Added comment field to match core dependencies

### LINKED ISSUE #48: Missing article content type generates issue in core views
image

Issue happens in `comments_recent` view:
Screenshot 2023-08-05 at 16 47 03

It's relation to Content is broken, as there are no content types with field entity reference to Comment entities.

### PR DESCRIPTION
**Pull request by twilderan**

### CODE REVIEW

**Review by jjroelofs — CHANGES_REQUESTED** [review]
Why would we have to add a comment field? I can't understand from the commit message why you choose this as a solution.
We don't want to use Drupal native comments here so I don't think this can be the right fix.

**Comment by twilderan** [comment]
@jjroelofs Recent comments view has a relationship to render nodes where comments were added. By default this profile has Recent comments view and 0 comments fields. There was an article content type before, but once it got deleted - this issue exists for all new users.

I thought to add back article content type, but later decided to add Comment field to Blog content type, which is hidden.

If you don't want to add comments to articles - better to disable Comments module on the installation (not sure what would be a solution for existing users - as they might already use comments block). This way we won't delete core view config, which users also might use.

**Comment by jjroelofs** [comment]
Yes, let's disable the comments module. I dont think we should do this in hook_update, instead we add in release notes that the comments module should be uninstalled if it is not used. We can say the same to people reporting the error.

**Comment by twilderan** [comment]
okay, I'll create another PR for it

**Comment by twilderan** [comment]
Replaced with https://github.com/dxpr/dxpr_marketing_cms/pull/50

**Pull request closed without merging**
